spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baby_sys 
    username: debian-sys-maint
    password: kuYA038hudThz5I6
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1000MB
  thymeleaf:
    cache: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
    - classpath:/static/
    - file:${path.upload}

logging:
  file:
    path: logs

server:
  tomcat:
    basedir: access
    accesslog:
      enabled: true

path:
  upload: /home/diao/qiqi/pic/         #文件上传路径